import express from "express";
import { getIssuedBooksByUser } from "../controllers/rentalController.js";
import { getIssuedBooksByDateRange } from "../controllers/rentalController.js";

import {
  issueBook,
  returnBook,
  getBookIssuanceDetails,
  getTotalRentByBook,
} from "../controllers/rentalController.js";

const router = express.Router();

// Route to issue a book
router.post("/issue", issueBook);

// Route to return a book
router.post("/return", returnBook);

// Route to get book issuance details by book name
router.get("/book-issuance/:bookName", getBookIssuanceDetails);

// Route to get total rent generated by a book
router.get("/total-rent/:bookName", getTotalRentByBook);

// Define the route for getting issued books by user
router.get("/issued-books/:userId", getIssuedBooksByUser);

// Define the route for getting books issued within a date range
router.post("/issued-books/date-range", getIssuedBooksByDateRange);

export default router;
